language: node_js
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
cache:
  directories:
    - ~/.npm
notifications:
  email: true
node_js:
  - '9'
after_success:
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
